version: "3.7"
services:
  patchman:
    build:
      context: .
      dockerfile: Dockerfile
    # TODO remove sleep and use wait-for-mysql script or mysql ping command instead
    command: bash -c "sleep 10 && patchman-manage makemigrations && patchman-manage migrate --run-syncdb && patchman-manage collectstatic --noinput"
    depends_on:
      - "database"
    expose:
      - '8080'
    volumes:
      - ./local_settings.py:/etc/patchman/local_settings.py
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
  database:
    image: mysql:5.7
    restart: always
    command: --init-file /init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 'changeme'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./init.sql:/init.sql
      - my-db:/var/lib/mysql
volumes:
  my-db:
